### ISSUE TITLE
掩码

### ISSUE THREAD

**Issue by zzgxpyy** [niudaii/crack#10]
可以考虑加一下掩码爆破.

**Comment by niudaii** [comment]
> 可以考虑加一下掩码爆破.

细说

**Comment by zzgxpyy** [comment]
> 

CIDR :   192.168.1.0/24

**Comment by niudaii** [comment]
> > 
> 
> CIDR : 192.168.1.0/24

crack 需要输入具体的 ip:port，CIDR 用在端口扫描，可以参考 [zpscan](https://github.com/niudaii/zpscan) 的 ipscan 模块。
