### ISSUE TITLE
Mac下rdp爆破问题

### ISSUE THREAD

**Issue by 1AI8olPw4** [niudaii/crack#9]
你好，我想问一下Mac环境下测试mssql等爆破可以，但是到rdp这一块无反馈（正确用户名密码），是因为Mac下缺少rdp相关组件吗？

**Comment by niudaii** [comment]
> 你好，我想问一下Mac环境下测试mssql等爆破可以，但是到rdp这一块无反馈（正确用户名密码），是因为Mac下缺少rdp相关组件吗？

1、我本地 rdp 是测试过的，可以查看测试用例。正常情况下不需要额外安装 rdp 相关组件。
2、你本地环境使用 Microsoft Remote Desktop Beta 等工具是否能正常连接爆破环境。
3、你可以使用 --debug 打开调试模式查看报错。
